Two optional parameters to control voltage limits
powsybl/powsybl-optimizer pull request #40
Opened 2023-11-03 15:13 UTC by p-arvy

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

Only one parameter is available (it decides low/high limits)

**What is the new behavior (if this is a feature change)?**
There is now two optional parameters to control the voltage limits.

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-11-09 15:36 UTC, annetill requested changes
You have to interface them in Java through the `OpenReacParameters`.

2023-11-10 12:40 UTC, annetill requested changes

2023-11-10 12:40 UTC, annetill commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +    private static final String MIN_VOLTAGE_LIMIT_CONSISTENCY_KEY = "consistent_min_voltage";
Maybe `MIN_PLAUSIBLE_LOW_VOLTAGE_LIMIT` and `MAX_PLAUSIBLE_LOW_VOLTAGE_LIMIT`. Is is more coherent with choices already made for open loadflow.

2023-11-10 12:40 UTC, annetill commented on open-reac/src/test/java/com/powsybl/openreac/OpenReacParametersTest.java
> +    void testMinMaxVoltageLimitIntegrityChecks() {
Can you provide a unit test that export the file with parameters and compare to a reference file stored in the ressources?

2023-11-23 10:29 UTC, klorel approved these changes

2023-11-23 14:09 UTC, annetill commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +    private Double objectiveDistance = 0.5; // between 0 and 100
Don't provide default value for a `Double` objective distance: it can be null without any issue depending on the objective chosen.

2023-11-23 14:09 UTC, annetill commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +    private Double minPlausibleLowVoltageLimit = 0.5; // in pu
Why a Double and not a double?

2023-11-23 14:10 UTC, annetill commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +        if (Double.isNaN(objectiveDistance) || objectiveDistance > 1 || objectiveDistance < 0) {
Comments suggest that it is a percentage.

2023-11-24 09:36 UTC, annetill approved these changes

2023-11-24 09:36 UTC, merged