Openreac - Add all modifications
powsybl/powsybl-optimizer pull request #5
Opened 2023-04-25 10:14 UTC by nicolas-pierr

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

See #2, this PR will implement all modifications appart from Generators

2023-05-25 14:47 UTC, annetill requested changes

2023-05-25 14:47 UTC, annetill commented on open-reac/src/main/java/com/powsybl/openreac/parameters/output/network/ShuntCompensatorNetworkOutput.java
> +public class ShuntCompensatorNetworkOutput extends AbstractNetworkOutput<ShuntCompensatorPositionModification> {
@nicolas-pierr indeed I think we have forgotten that a shunt can be reconnected by the optimizer. And we don't have any modification for that.

2023-06-26 13:07 UTC, geofjamg approved these changes

2023-06-26 13:21 UTC, annetill approved these changes

2023-06-26 13:23 UTC, merged