Add synthetic and detailed logs for missing or inconsistent voltage levels limits.
powsybl/powsybl-optimizer pull request #68
Opened 2024-04-26 09:24 UTC by FranckLecuyer

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

When there are voltage levels without limits, and also when there are inconsistencies in the limits (limit < 0 or low limit > high limit),
an exception is just thrown, and we have no information about the concerned voltage levels.  

**What is the new behavior (if this is a feature change)?**
Synthetic and detailed reports are now created for missing or inconsistent voltage levels limits, before the exception is thrown, in order to help the user to correct his data.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-05-13 13:32 UTC, So-Fras requested changes
Thanks for adding this feature. I made some comments and there are new code smells too, mainly about maintainability. Is it possible to refactor the methods mentioned by Sonar?

2024-05-13 15:45 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/OpenReacRunner.java
> +        checkParameters(network, variantId, parameters, config, manager, Reports.createParametersIntegrityReporter(reportNode, network.getId()));
Changed

2024-05-13 15:45 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/Reports.java
> +    public static ReportNode createParametersIntegrityReporter(ReportNode reportNode, String networkId) {
Renamed

2024-05-13 15:45 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/Reports.java
> +            .withMessageTemplate("openReacParametersIntegrity", "Open reac parameters integrity on network '${networkId}'")
Changed

2024-05-13 15:46 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/OpenReacRunner.java
> +        parameters.checkIntegrity(network, reportNode);
Changed

2024-05-13 15:47 UTC, FranckLecuyer commented
> Thanks for adding this feature. I made some comments and there are new code smells too, mainly about maintainability. Is it possible to refactor the methods mentioned by Sonar?

Refactoring done to remove sonar issues.

2024-05-16 07:48 UTC, So-Fras approved these changes

2024-05-16 08:04 UTC, merged