Modify default scaling values in AMPL
powsybl/powsybl-optimizer pull request #72
Opened 2024-06-05 17:14 UTC by p-arvy

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-06-17 11:59 UTC, So-Fras requested changes
![image](https://github.com/powsybl/powsybl-optimizer/assets/93923177/23419a37-d8c0-4a38-aec7-6ec36007a2a5)

It seems to me that the documentation is not up-to-date with your modifications.

2024-06-25 10:40 UTC, p-arvy commented
Hello @So-Fras , the default scaling value for transformers variables is different between AMPL (1e-1) and Java (1e-3). This is the case for not forcing the scaling of a user who only wants to run the AMPL code (not from the OpenReac Java interface). 

I think it's more appropriate to put the default value of the java interface in the documentation, but I've added a sentence to indicate that the values can be different. Thank you for the comment!

2024-06-25 11:28 UTC, So-Fras approved these changes

2024-06-26 13:30 UTC, klorel approved these changes

2024-06-27 07:53 UTC, merged