Fix message key in reports for voltage levels missing limits
powsybl/powsybl-optimizer pull request #78
Opened 2024-08-12 12:58 UTC by FranckLecuyer

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

The same message key is used when reporting missing voltage limits in all cases (missing high limits, missing low limits or missing high and low limits).

**What is the new behavior (if this is a feature change)?**
We use now a specific message key for missing high limits, missing low limits or missing high and low limits.

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-08-13 15:30 UTC, ayolab approved these changes

2024-08-26 07:52 UTC, So-Fras requested changes
Thanks for the fix, I just noted some typos.

2024-08-26 07:52 UTC, So-Fras commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +                    String messageKey = "voltageLevelWithBothMissingLimits";
```suggestion
                    String messageKey = "voltageLevelWithBothLimitsMissing";
```

2024-08-26 07:52 UTC, So-Fras commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +                        messageKey = "voltageLevelWithHighMissingLimits";
```suggestion
                        messageKey = "voltageLevelWithUpperLimitMissing";
```

2024-08-26 07:52 UTC, So-Fras commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +                        messageKey = "voltageLevelWithLowMissingLimits";
```suggestion
                        messageKey = "voltageLevelWithLowerLimitMissing";
```

2024-08-26 09:33 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +                    String messageKey = "voltageLevelWithBothMissingLimits";
Done

2024-08-26 09:33 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +                        messageKey = "voltageLevelWithHighMissingLimits";
Done

2024-08-26 09:33 UTC, FranckLecuyer commented on open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
> +                        messageKey = "voltageLevelWithLowMissingLimits";
Done

2024-08-28 07:58 UTC, merged