[WIP] Refactor OpenReac optimization tests
powsybl/powsybl-optimizer pull request #83
Opened 2024-11-27 17:49 UTC by p-arvy

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-12-20 15:06 UTC, So-Fras requested changes
Thanks for refactoring the tests!

2024-12-20 15:06 UTC, So-Fras commented on open-reac/src/test/java/com/powsybl/openreac/optimization/OpenReacOptimizationAndLoadFlowTest.java
> +    public static Network create() {
It is a bit confusing that this method is named the same than another one in ShuntNetworkFactory (also used in tests).

So maybe change the `public` into a `private` and change the name into a more explicit one?

2024-12-30 11:07 UTC, p-arvy commented on open-reac/src/test/java/com/powsybl/openreac/optimization/AbstractOpenReacRunnerTest.java
> +    void runAndApplyAllModifications(Network network, String subFolder, OpenReacParameters parameters,
Done, thanks for the remark.

2024-12-30 11:07 UTC, p-arvy commented on open-reac/src/test/java/com/powsybl/openreac/optimization/AbstractOpenReacRunnerTest.java
> +    void setDefaultVoltageLimits(Network network) {
Same.

2024-12-30 11:20 UTC, p-arvy commented on open-reac/src/test/java/com/powsybl/openreac/optimization/OpenReacOptimizationAndLoadFlowTest.java
> +    public static Network create() {
The two `create` functions differ in their use of a linear or nonlinear model for the shunt. So I put both methods in the `ShuntNetworkFactory` class, and differentiated them by name. 

This resolves [this comment](https://github.com/powsybl/powsybl-optimizer/pull/88#discussion_r1894102590) in another PR.

2025-01-06 15:54 UTC, So-Fras approved these changes

2025-01-08 08:59 UTC, merged